[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "Ply",
]
build-backend = "setuptools.build_meta"
[tool.black]
line-length = 130
target-version = ['py37']
include = '\.pyi?$'
exclude = '''
/(
    \.git
| \.hg
| \.github
| \.mypy_cache
| \.tox
| \.venv
| _build
| buck-out
| build
| __pycache__
| dist
| \.history
| \.idea
| \.chat
| \.ruff_cache
| \.trunk
)/
'''

[tool.flake8]
max-line-length = 130
extend-ignore = [
    "ANN",
    "ANN101",  # Missing type annotation for {name} in method
    "ANN401",  # Dynamically typed expressions (typing.Any) are disallowed in {name}
    "D401",    # First line of docstring should be in imperative mood
    "E501",    # line too long
    "FBT001",  # Boolean positional arg in function definition
    "FBT002",  # Boolean default value in function definition
    "FIX004",  # Line contains HACK, consider resolving the issue
    "PD901",   # df is a bad variable name. Be kinder to your future self.
    "PLR0913", # Too many arguments to function call (N > 5)
    "PLR2004", # Magic value used in comparison, consider replacing X with a constant variable
    "SLF001",  # Private member accessed
    "D101",
    "D102",
    "D103",
    "D107",
    "D205",
    "D400",
    "D403",
    "D415",
    "D417",
    "D205",
    "D212",
    "D200",
    "PLR5501",
    "PLW2901"
]
max-complexity = 25

[tool.isort]
atomic = true
profile = "black"
line_length = 130
skip_gitignore = true
