[build-system]
requires = [
    "setuptools>=42",
    "wheel",
]
build-backend = "setuptools.build_meta"
[tool.black]
line-length = 130
target-version = ['py37']
include = '\.pyi?$'
exclude = '''
/(
    \.git
| \.hg
| \.github
| \.mypy_cache
| \.tox
| \.venv
| _build
| buck-out
| build
| __pycache__
| dist
| \.history
| \.idea
| \.chat
| \.ruff_cache
| \.trunk
)/
'''

[tool.flake8]
exclude = [".git", "__pycache__", "dist"]
max-line-length = 130
max-complexity = 25

[tool.isort]
atomic = true
profile = "black"
line_length = 130
skip_gitignore = true
