name: Forward Commits to Bleeding-Edge

on:
  push:
    branches:
      - '*'
      - '!bleeding-edge'

jobs:
  merge:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, '[skip-edge]') == false

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Merge to Bleeding-Edge
      run: |
        git checkout bleeding-edge
        git merge ${{ github.ref }}
        git push origin bleeding-edge