name: Toolkit Install Test

on: [push, pull_request]

jobs:
  install-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'

    - name: Install toolkit
      run: pip install ./toolkit

    - name: Test pykotor installation
      run: python -c "import pykotor"

    - name: Test pykotor installation
      run: python -c "import toolset"
