name: Python 3.12 unittest

on: [push, pull_request]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r Libraries/PyKotor/requirements.txt

    - name: Run unittest on files in pykotor/tests
      run: |
        cd Libraries/PyKotor
        python -m unittest discover -s src/tests -p 'test_*.py' -v
